### ISSUE TITLE
请问，邮箱那块，py脚本为什么不运行

### ISSUE THREAD

**Issue by mxf-2023** [LIRUILONGS/hros#10]

**Comment by LIRUILONGS** [comment]
@mxf-2023  嗯，上次有小伙伴提交 PR了，把那部分代码干掉了...

![image](https://user-images.githubusercontent.com/46131861/232970651-233392d1-68f1-4bfc-8ae4-aac15469ee39.png)

**Comment by mxf-2023** [comment]
我把这个代码加上了，还是调不了脚本
![image](https://user-images.githubusercontent.com/66150433/232979125-b3ddb935-66ea-49d9-8c67-be7924ac0f81.png)
### ****

**Comment by lunasaw** [comment]
这个需要在py文件中加入响应的配置，并且保证单元测试Runtime.getRunTime().exec(args) 对应的py命令可行

**Comment by mxf-2023** [comment]
[python, src\main\java\com\liruilong\hros\script\emailpy.py, 3377192341@qq.com, saf, 人事管理系统测试##员工入职]
这个是Runtime.getRunTime().exec(args)传来的参数
py文件除了邮箱信息外，其他的没有改动，不知道要加什么配置

**Comment by mxf-2023** [comment]
Runtime.getRunTime().exec(args)传进去的参数---》[python, src\main\java\com\liruilong\hros\script\emailpy.py, [3377192341@qq.com](mailto:3377192341@qq.com), saf, 人事管理系统测试##员工入职]
感觉没什么问题，但无法执行脚本

**Comment by lunasaw** [comment]
你单测这个脚本试试
